# Generated by Django 3.2.9 on 2021-11-20 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('dinero', models.PositiveIntegerField(default=10000)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
