# Generated by Django 3.2.9 on 2021-11-21 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruleta_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
